# Generated by Django 2.2.1 on 2019-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('name',), name='name_unique_constraint'),
        ),
    ]
